# User config
author: "Lyonel Zamora"
tagline: ""
description: "Recent Computer Science (Computer Games) Grad that is actively seeking for a job as a developer! <br> If i'm not coding you can find me playing guitar and making music!  "
keywords: ""
email: "lyonelz516@gmail.com"
linkedin: "https://linkedin.com/in/lyonelz96"
github: "https://github.com/lyonelz96"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed